### ISSUE TITLE
Shadowing defines Z_PASTE_31 and Z_JOIN_31

### ISSUE THREAD

**Issue by lmancini** [redcode/Z#2]
Hi, in https://github.com/redcode/Z/blob/3c352b45c941695fa00f0be1731bc646cd9bc5ed/API/Z/macros/pasting.h#L101 and https://github.com/redcode/Z/blob/3c352b45c941695fa00f0be1731bc646cd9bc5ed/API/Z/macros/pasting.h#L133 you have two defines that are immediately shadowed by the next line. I think they are typos and should be `Z_PASTE_30` and `Z_JOIN_30`.

**Comment by redcode** [comment]
Thank you for the tip!

I've fixed it in the commit [161e454fb085164ea9b3765be43aac3e1fad20c3](https://github.com/redcode/Z/commit/161e454fb085164ea9b3765be43aac3e1fad20c3).

I realized this some time ago and corrected it in the "v0.1" branch I'm working on now.
