### ISSUE TITLE
2 redundant and 30 conflicting definitions in API/Z

### ISSUE THREAD

**Issue by cpcitor** [redcode/Z#2]
Hi,

Duplicate definitions

```
API/Z/keys/chemistry.h:15:#define Z_KEY_BITS_ELECTRICAL_TYPE 8
API/Z/keys/chemistry.h:23:#define Z_KEY_BITS_ELECTRICAL_TYPE 8
```

Conflicting definitions

These might make sense from a perspective of parsing these files by anything else, but when parsed by a standard C/C++ preprocessor, only the last definition will be retained.

```
API/Z/formats/character set/Unicode.h:20:#define Z_UNICODE_BELL			      0x0007
API/Z/formats/character set/Unicode.h:28300:#define Z_UNICODE_BELL										 0x1F514
```

```
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:130:#define Z_SNES_GAME_PAK_LICENSE_ACCLAIM				  81
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:216:#define Z_SNES_GAME_PAK_LICENSE_ACCLAIM				 219
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:87:#define Z_SNES_GAME_PAK_LICENSE_CAPCOM				   8
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:213:#define Z_SNES_GAME_PAK_LICENSE_CAPCOM				 216
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:95:#define Z_SNES_GAME_PAK_LICENSE_ELECTRONIC_ARTS			  19
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:143:#define Z_SNES_GAME_PAK_LICENSE_ELECTRONIC_ARTS			 105
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:108:#define Z_SNES_GAME_PAK_LICENSE_ENIX				  38
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:189:#define Z_SNES_GAME_PAK_LICENSE_ENIX				 180
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:99:#define Z_SNES_GAME_PAK_LICENSE_HUDSON_SOFT			  24
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:236:#define Z_SNES_GAME_PAK_LICENSE_HUDSON_SOFT			 255
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:89:#define Z_SNES_GAME_PAK_LICENSE_JALECO				  10
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:220:#define Z_SNES_GAME_PAK_LICENSE_JALECO				 224
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:110:#define Z_SNES_GAME_PAK_LICENSE_KEMCO				  40
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:156:#define Z_SNES_GAME_PAK_LICENSE_KEMCO				 127
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:197:#define Z_SNES_GAME_PAK_LICENSE_KEMCO				 194
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:98:#define Z_SNES_GAME_PAK_LICENSE_KOEI				  23
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:161:#define Z_SNES_GAME_PAK_LICENSE_KOEI				 132
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:202:#define Z_SNES_GAME_PAK_LICENSE_KOEI				 200
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:159:#define Z_SNES_GAME_PAK_LICENSE_NAMCO				 130
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:186:#define Z_SNES_GAME_PAK_LICENSE_NAMCO				 175
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:83:#define Z_SNES_GAME_PAK_LICENSE_NINTENDO			   1
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:115:#define Z_SNES_GAME_PAK_LICENSE_NINTENDO			  51
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:105:#define Z_SNES_GAME_PAK_LICENSE_SUNSOFT				  33
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:192:#define Z_SNES_GAME_PAK_LICENSE_SUNSOFT				 187
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:168:#define Z_SNES_GAME_PAK_LICENSE_TAKARA				 144
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:181:#define Z_SNES_GAME_PAK_LICENSE_TAKARA				 167
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:101:#define Z_SNES_GAME_PAK_LICENSE_TECMO				  28
API/Z/hardware/storage medium/ROM cartridge/SNES Game Pak.h:176:#define Z_SNES_GAME_PAK_LICENSE_TECMO				 155
```

Spotted while reading your work (nice work), then manually reviewing doing in emacs a grep with this custom command:

`find . -iname "*.h*" | while read N ; do LC_ALL=C grep -Eo '^\s*#define\s+\S+' "$N" | sort | uniq -d | grep . | while read LINE ; do grep -nH "$LINE" "$N" ; done ; done`

**Comment by redcode** [comment]
Please, read this: https://github.com/redcode/Z/pull/1#issuecomment-2480563531

**Comment by cpcitor** [comment]
> Please, read this: [#1 (comment)](https://github.com/redcode/Z/pull/1#issuecomment-2480563531)

Done. 

FWIW I've ported your Z80_XCF_Flavor test to the Amstrad CPC, it's on https://github.com/cpcitor/Z80_XCF_Flavor_CPC . Have a nice day!

**Comment by cpcitor** [comment]
I also posted about it on https://www.cpcwiki.eu/forum/programming/program-that-tests-z80-scfccf-undefined-behavior-on-flags .

You took care about the ñ character in your name. As you can see, I took care of it, too, when porting to the CPC.

**Comment by redcode** [comment]
Thank you 😃

Hey, note that the ST CMOS behavior "detected" by the test is not correct according to recent research, and there may be more behaviors, possibly on NEC CMOS models and others.

More info here: https://github.com/redcode/Z80_XCF_Flavor/issues/2
and here: https://github.com/hoglet67/Z80Decoder/wiki/Unstable-CCF-SCF-Behaviour
and also here: https://zx-pk.ru/threads/35936-zagadka-plavayushchikh-flagov-scf-ccf-raskryta!.html

I'm a bit busy lately, but I plan to test my entire Z80 CPU collection soon on a ZX Spectrum Issue 3B repro board that I soldered up:

![imagen](https://github.com/user-attachments/assets/11472f17-40b4-4a56-9972-b0e5e0bd2111)

**Comment by redcode** [comment]
I forgot to mention that I maintain tests collections for the Z80 CPU and the Sinclair ZX Spectrum here:

https://github.com/redcode/Z80/wiki/Tests
https://github.com/redcode/ZXSpectrum/wiki/Tests

You might find other tests that interest you as well...

**Comment by cpcitor** [comment]
Thanks for those extra details.
Regarding [redcode/Z80_XCF_Flavor#2](https://github.com/redcode/Z80_XCF_Flavor/issues/2) I'm not really surprised, as I knew there was some analog fuzziness involved.
Regarding https://zx-pk.ru/threads/35936-zagadka-plavayushchikh-flagov-scf-ccf-raskryta!.html some users feel this is useless. IMHO it is useful to detect emulation, but more importantly for the fun and learning.
https://github.com/redcode/Z80/wiki/Tests is the wiki where I came from and saw all those tests. Alas a number of them have little to no description, some (e.g. https://github.com/redcode/Z80/wiki/ED777F https://github.com/redcode/Z80/wiki/FDDD2 ) link to private Discord messages (my guess is Discord will not stand the test of time, that would need massive public archives).
Kudos for your contribution to the impressive https://github.com/pdsmart/tzpuFusionX .
I subscribed to your repos, will get notified when the tests are updated. I think we can close this issue.

**Comment by redcode** [comment]
> ... link to private Discord messages...

Most of the tests with discord links have been posted and discussed in the ZX Spectrum discord server:
https://discord.com/invite/eJk5TtSkYb

That server is frequented by test and emulator authors and is where much of the Z80 research from the ZX Spectrum community has been conducted.
