### ISSUE TITLE
There's a trailing #endif

### ISSUE THREAD

**Issue by fmixolydian** [redcode/Z#3]
I tried to build https://github.com/redcode/6502 and it failed with the following error:
```
/usr/local/include/Z/inspection/compiler/modules/GCC.h:1367:2: error: #endif without #if
 1367 | #endif /* _Z_inspection_modules_compiler_GCC_H_ */
      |  ^~~~~
```

It's clear that somewhere in the file, there's a trailing #endif.
Removing the last `#endif` in the file lets it compile, although I'm afraid the erroneous line may be somewhere else in the code.

**Comment by redcode** [comment]
It should be fixed with https://github.com/redcode/Z/commit/88026d3ebb16a129d7b1c8306df24de246ba9562, try again.

This repo is an old snapshot of https://github.com/redcode/Zeta. The 6502 emulator will be migrated to Zeta in the near future.
